STYLE header markup
unknownburphy/pdf_summary_frontend pull request #9
Opened 2023-07-22 06:54 UTC by rannie-kim

- 헤더 마크업

2023-07-23 05:45 UTC, minhouu commented
@rannie-kim 
main말고 dev로 merge해야될 것 같아요 낄낄

2023-07-24 05:53 UTC, unknownburphy requested changes
dev로 날려주세용

2023-07-24 06:11 UTC, rannie-kim commented
했어염

2023-07-24 08:14 UTC, unknownburphy approved these changes
너무 수고하셨습니다!

2023-07-24 08:14 UTC, unknownburphy commented on src/routes/HomePage.jsx
> +            className="flex flex-col items-center justify-center w-full h-64 border-[3px] border-key border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:b
dark:hover:bg-bray-800 이 중복되는 것 같습니당!!

```suggestion
            className="flex flex-col items-center justify-center w-full h-64 border-[3px] border-key border-dashed rounded-lg cursor-pointer bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600"
```

2023-07-24 08:14 UTC, unknownburphy commented on src/routes/HomePage.jsx
> +          onDrop={handleDrop}
이런 이벤트가 있는지 처음 알았네요 많이 배워갑니다 LGTM!

2023-07-24 08:50 UTC, merged